### ISSUE TITLE
Build coreboot for apu2 -- mkdir: cannot create directory 'build': Permission denied

### ISSUE THREAD

**Issue by clement-analogue** [pcengines/pce-fw-builder#34]
In the last tag 1.52.3, build.sh fails at stage `Build coreboot for apu2` with the following error `mkdir: cannot create directory 'build': Permission denied`. Here the full log

```
$ ./build.sh release v4.11.0.6 apu2
Cloning into 'release/coreboot'...
remote: Counting objects: 194, done
remote: Finding sources: 100% (180/180)
remote: Total 541449 (delta 2), reused 541293 (delta 2)
Receiving objects: 100% (541449/541449), 137.31 MiB | 5.69 MiB/s, done.
Resolving deltas: 100% (414215/414215), done.
Checking out files: 100% (15011/15011), done.
Submodule '3rdparty/amd_blobs' (https://review.coreboot.org/amd_blobs) registered for path '3rdparty/amd_blobs'
Submodule 'arm-trusted-firmware' (https://review.coreboot.org/arm-trusted-firmware.git) registered for path '3rdparty/arm-trusted-firmware'
Submodule '3rdparty/blobs' (https://review.coreboot.org/blobs.git) registered for path '3rdparty/blobs'
Submodule '3rdparty/chromeec' (https://review.coreboot.org/chrome-ec.git) registered for path '3rdparty/chromeec'
Submodule '3rdparty/ffs' (https://review.coreboot.org/ffs.git) registered for path '3rdparty/ffs'
Submodule '3rdparty/fsp' (https://review.coreboot.org/fsp.git) registered for path '3rdparty/fsp'
Submodule 'intel-microcode' (https://review.coreboot.org/intel-microcode.git) registered for path '3rdparty/intel-microcode'
Submodule 'libgfxinit' (https://review.coreboot.org/libgfxinit.git) registered for path '3rdparty/libgfxinit'
Submodule 'libhwbase' (https://review.coreboot.org/libhwbase.git) registered for path '3rdparty/libhwbase'
Submodule 'opensbi' (https://review.coreboot.org/opensbi.git) registered for path '3rdparty/opensbi'
Submodule 'vboot' (https://review.coreboot.org/vboot.git) registered for path '3rdparty/vboot'
Submodule 'util/nvidia-cbootimage' (https://review.coreboot.org/nvidia-cbootimage.git) registered for path 'util/nvidia/cbootimage'
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/amd_blobs'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/arm-trusted-firmware'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/blobs'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/chromeec'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/ffs'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/fsp'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/intel-microcode'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/libgfxinit'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/libhwbase'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/opensbi'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/3rdparty/vboot'...
Cloning into '/home/clement/pce-fw-builder/release/coreboot/util/nvidia/cbootimage'...
Submodule path '3rdparty/amd_blobs': checked out 'dcfc2275a7b7c195a7afb657e9829b6bd1b86538'
Submodule path '3rdparty/arm-trusted-firmware': checked out 'ace23683beb81354d6edbc61c087ab8c384d0631'
Submodule path '3rdparty/blobs': checked out '7ad2d22452225a14c19b17570cb77920d8fc81a5'
Submodule path '3rdparty/chromeec': checked out 'a1afae4e002a3eccd7835ac898259b0690e9e61a'
Submodule path '3rdparty/ffs': checked out '3ec70fbc458e32eef0d0b1de79688b4dc48cbd57'
Submodule path '3rdparty/fsp': checked out '0bc2b07eab29a8a75cd084963c285ee5434e6666'
Submodule path '3rdparty/intel-microcode': checked out '33b7b2f3817e362111cd91910026ab8907f21710'
Submodule path '3rdparty/libgfxinit': checked out '2e87c0d40a387c5b1f1afd3ce61ecdc7dad0e3e8'
Submodule path '3rdparty/libhwbase': checked out 'bd0ed91cb985a697033edd9fd62d322aa017e791'
Submodule path '3rdparty/opensbi': checked out '215421ca610a64b8ec188c96ea8588ae2de41fb7'
Submodule path '3rdparty/vboot': checked out '3aab301473ec0b95f109a245efeadc20c3b7d57d'
Submodule path 'util/nvidia/cbootimage': checked out '65a6d94dd5f442578551e0a81ecbe5235e673fd4'
remote: Enumerating objects: 2965, done.
remote: Counting objects: 100% (2965/2965), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 9323 (delta 2907), reused 2944 (delta 2900), pack-reused 6358
Receiving objects: 100% (9323/9323), 3.46 MiB | 2.90 MiB/s, done.
Resolving deltas: 100% (6622/6622), completed with 917 local objects.
From https://github.com/pcengines/coreboot
 * [new branch]            apu1_power_fail_fix            -> pcengines/apu1_power_fail_fix
 * [new branch]            coreboot-4.0.x                 -> pcengines/coreboot-4.0.x
 * [new branch]            coreboot-4.5.x                 -> pcengines/coreboot-4.5.x
 * [new branch]            coreboot-4.6.x                 -> pcengines/coreboot-4.6.x
 * [new branch]            develop                        -> pcengines/develop
 * [new branch]            disable_lpcclk0                -> pcengines/disable_lpcclk0
 * [new branch]            fosdem2020                     -> pcengines/fosdem2020
 * [new branch]            ipxe_landing_zone              -> pcengines/ipxe_landing_zone
 * [new branch]            ipxe_multiboot2                -> pcengines/ipxe_multiboot2
 * [new branch]            master                         -> pcengines/master
 * [new branch]            new_spi_and_bootorder          -> pcengines/new_spi_and_bootorder
 * [new branch]            pcengines_trenchboot_4.11.x    -> pcengines/pcengines_trenchboot_4.11.x
 * [new branch]            pcengines_trenchboot_v4.10.0.2 -> pcengines/pcengines_trenchboot_v4.10.0.2
 * [new branch]            release                        -> pcengines/release
 * [new branch]            tianocore_vUDK2018             -> pcengines/tianocore_vUDK2018
 * [new branch]            tpm2_uefi                      -> pcengines/tpm2_uefi
 * [new branch]            vpd_port                       -> pcengines/vpd_port
 * [new tag]               v4.0.30                        -> v4.0.30
 * [new tag]               v4.11.0.6                      -> v4.11.0.6
 * [new tag]               v4.5.8                         -> v4.5.8
 * [new tag]               v4.6.10                        -> v4.6.10
 * [new tag]               v4.7.0                         -> v4.7.0
 * [new tag]               apu2b-20160304                 -> apu2b-20160304
 * [new tag]               v4.0.1                         -> v4.0.1
 * [new tag]               v4.0.1.1                       -> v4.0.1.1
 * [new tag]               v4.0.10                        -> v4.0.10
 * [new tag]               v4.0.11                        -> v4.0.11
 * [new tag]               v4.0.12                        -> v4.0.12
 * [new tag]               v4.0.13                        -> v4.0.13
 * [new tag]               v4.0.14                        -> v4.0.14
 * [new tag]               v4.0.15                        -> v4.0.15
 * [new tag]               v4.0.16                        -> v4.0.16
 * [new tag]               v4.0.17                        -> v4.0.17
 * [new tag]               v4.0.18                        -> v4.0.18
 * [new tag]               v4.0.19                        -> v4.0.19
 * [new tag]               v4.0.2                         -> v4.0.2
 * [new tag]               v4.0.20                        -> v4.0.20
 * [new tag]               v4.0.21                        -> v4.0.21
 * [new tag]               v4.0.22                        -> v4.0.22
 * [new tag]               v4.0.23                        -> v4.0.23
 * [new tag]               v4.0.24                        -> v4.0.24
 * [new tag]               v4.0.25                        -> v4.0.25
 * [new tag]               v4.0.26                        -> v4.0.26
 * [new tag]               v4.0.27                        -> v4.0.27
 * [new tag]               v4.0.28                        -> v4.0.28
 * [new tag]               v4.0.29                        -> v4.0.29
 * [new tag]               v4.0.3                         -> v4.0.3
 * [new tag]               v4.0.4                         -> v4.0.4
 * [new tag]               v4.0.5                         -> v4.0.5
 * [new tag]               v4.0.6                         -> v4.0.6
 * [new tag]               v4.0.7                         -> v4.0.7
 * [new tag]               v4.0.7.1                       -> v4.0.7.1
 * [new tag]               v4.0.7.2                       -> v4.0.7.2
 * [new tag]               v4.0.8                         -> v4.0.8
 * [new tag]               v4.0.9                         -> v4.0.9
 * [new tag]               v4.10.0.0                      -> v4.10.0.0
 * [new tag]               v4.10.0.1                      -> v4.10.0.1
 * [new tag]               v4.10.0.2                      -> v4.10.0.2
 * [new tag]               v4.10.0.3                      -> v4.10.0.3
 * [new tag]               v4.11.0.1                      -> v4.11.0.1
 * [new tag]               v4.11.0.2                      -> v4.11.0.2
 * [new tag]               v4.11.0.3                      -> v4.11.0.3
 * [new tag]               v4.11.0.4                      -> v4.11.0.4
 * [new tag]               v4.11.0.5                      -> v4.11.0.5
 * [new tag]               v4.5.2                         -> v4.5.2
 * [new tag]               v4.5.3                         -> v4.5.3
 * [new tag]               v4.5.3.1                       -> v4.5.3.1
 * [new tag]               v4.5.4                         -> v4.5.4
 * [new tag]               v4.5.5                         -> v4.5.5
 * [new tag]               v4.5.5.1                       -> v4.5.5.1
 * [new tag]               v4.5.5.2                       -> v4.5.5.2
 * [new tag]               v4.5.6                         -> v4.5.6
 * [new tag]               v4.5.7                         -> v4.5.7
 * [new tag]               v4.6.0                         -> v4.6.0
 * [new tag]               v4.6.1                         -> v4.6.1
 * [new tag]               v4.6.2                         -> v4.6.2
 * [new tag]               v4.6.3                         -> v4.6.3
 * [new tag]               v4.6.4                         -> v4.6.4
 * [new tag]               v4.6.5                         -> v4.6.5
 * [new tag]               v4.6.6                         -> v4.6.6
 * [new tag]               v4.6.7                         -> v4.6.7
 * [new tag]               v4.6.8                         -> v4.6.8
 * [new tag]               v4.6.9                         -> v4.6.9
 * [new tag]               v4.8.0.1                       -> v4.8.0.1
 * [new tag]               v4.8.0.2                       -> v4.8.0.2
 * [new tag]               v4.8.0.3                       -> v4.8.0.3
 * [new tag]               v4.8.0.4                       -> v4.8.0.4
 * [new tag]               v4.8.0.5                       -> v4.8.0.5
 * [new tag]               v4.8.0.6                       -> v4.8.0.6
 * [new tag]               v4.8.0.7                       -> v4.8.0.7
 * [new tag]               v4.9.0.1                       -> v4.9.0.1
 * [new tag]               v4.9.0.2                       -> v4.9.0.2
 * [new tag]               v4.9.0.3                       -> v4.9.0.3
 * [new tag]               v4.9.0.4                       -> v4.9.0.4
 * [new tag]               v4.9.0.5                       -> v4.9.0.5
 * [new tag]               v4.9.0.6                       -> v4.9.0.6
 * [new tag]               v4.9.0.7                       -> v4.9.0.7
warning: Submodule in commit f41f93946311b5dedf8f5a714aeb6c2b315cef73 at path: '(null)' collides with a submodule named the same. Skipping it.
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Total 9 (delta 8), reused 8 (delta 8), pack-reused 1
Unpacking objects: 100% (9/9), done.
From https://github.com/pcengines/coreboot
 * [new tag]               v4.5.1     -> v4.5.1
Checking out files: 100% (8814/8814), done.
Note: checking out 'v4.11.0.6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f658838fbb Merge pull request #399 from pcengines/rel_4.11.0.6
Submodule path '3rdparty/amd_blobs': checked out '17d028869899e1ea0f6f385501088f7623121fcb'
Submodule path '3rdparty/intel-microcode': checked out '1dd14da6d1ea5cfbd95923653f31c04aac3aa655'
Submodule path '3rdparty/libgfxinit': checked out 'cdbfce275777f2fd142e3a3c73469807a4c40207'
Submodule path '3rdparty/vboot': checked out '55154620f4aa3bba9eaaf09f5186a52a48720025'
Release apu2 build coreboot mainline
Build coreboot for apu2
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
/bin/sh: 1: cannot create .dependencies: Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
/bin/sh: 1: cannot create .dependencies: Permission denied
cp: cannot create regular file '.config': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
Error: Expected config file (/home/coreboot/coreboot/.config) not present.
Please specify a config file or run 'make menuconfig' to
generate a new config file.
make: *** [Makefile:159: real-all] Error 1
cp: cannot stat 'coreboot/build/coreboot.rom': No such file or directory
sha256sum: apu2_v4.11.0.6.rom: No such file or directory
```

**Comment by miczyg1** [comment]
@clement-analogue the `/home/coreboot/coreboot` is hardcoded because it is a constant path inside the container where the coreboot source code is mounted. During the build process the container cannot create any file inside the coreboot directory, according to the logs. The reason may be that the UID of `clement` user is different than the UID of the user `coreboot` inside the container. This leads to permission issues shown on the logs. The UID of the `coreboot` user is 1000.

I will prepare a pull request that could potentially fix your problem.

**Comment by clement-analogue** [comment]
Yes, I edited my post after I saw the mapping in docker. Indeed, the id of my user is not 1000 :)

**Comment by clement-analogue** [comment]
I can confirm id mapping is the issue. I log in with the user having id 1000 and it is working now. As we are working in a multi-user environment, proper user mapping will be use full :)

**Comment by macpijan** [comment]
An example of how dynamic UID/GID can be assigned:
* in the run script env variables with UID/GID are exported into containter's env: https://github.com/siemens/kas/blob/master/kas-docker#L260
* In container's entrypoint user is created (at runtime) with given UID/GID: https://github.com/siemens/kas/blob/master/docker-entrypoint#L22

**Comment by miczyg1** [comment]
@macpijan can we pass the `-u $UID` to the docker commandline to always use the user ID of the caller? I wonder if it will conflict with coreboot user inside container in any way?

**Comment by macpijan** [comment]
It may potentially conflict. In the mentioned exaple, there is no "builder" (`coreboot` in tour case) user created at container build time. Because ID of such user has to be determined at container build time and such issues with privileges appear.

Instead, the "build" user is created at runtime in the entrypoint (with the same UID as the user running the container): https://github.com/siemens/kas/blob/master/container-entrypoint#L28

**Comment by miczyg1** [comment]
@macpijan there is a coreboot "builder" user created in the parent coreboot-sdk container. We may add our own entrypoint to create such user (and possibly delete previously created coreboot user with ID 1000).

**Comment by macpijan** [comment]
@miczyg1 That should do the trick and resolve the permission issues for users with UID != 1000

**Comment by pkonkol** [comment]
I've made PR that will fix this problem:
https://github.com/pcengines/pce-fw-builder/pull/39

**Comment by vecinohk** [comment]
I have the same problem - please is there a way to solve it or do I have to wait for a new version to be released?

**Comment by vecinohk** [comment]
`root@debian10:~/bios# git clone https://github.com/pcengines/pce-fw-builder.git
Cloning into 'pce-fw-builder'...
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 295 (delta 33), reused 43 (delta 17), pack-reused 227
Receiving objects: 100% (295/295), 142.21 KiB | 791.00 KiB/s, done.
Resolving deltas: 100% (144/144), done.

root@debian10:~/bios/pce-fw-builder# ./build.sh release v4.13.0.1 apu2
Cloning into 'release/coreboot'...
remote: Counting objects: 1591, done
remote: Finding sources: 100% (1576/1576)
remote: Total 593904 (delta 266), reused 593211 (delta 266)
Receiving objects: 100% (593904/593904), 157.95 MiB | 7.04 MiB/s, done.
Resolving deltas: 100% (443831/443831), done.
Submodule '3rdparty/amd_blobs' (https://review.coreboot.org/amd_blobs) registered for path '3rdparty/amd_blobs'
Submodule 'arm-trusted-firmware' (https://review.coreboot.org/arm-trusted-firmware.git) registered for path '3rdparty/arm-trusted-firmware'
Submodule '3rdparty/blobs' (https://review.coreboot.org/blobs.git) registered for path '3rdparty/blobs'
Submodule '3rdparty/chromeec' (https://review.coreboot.org/chrome-ec.git) registered for path '3rdparty/chromeec'
Submodule '3rdparty/cmocka' (https://review.coreboot.org/cmocka.git) registered for path '3rdparty/cmocka'
Submodule '3rdparty/ffs' (https://review.coreboot.org/ffs.git) registered for path '3rdparty/ffs'
Submodule '3rdparty/fsp' (https://review.coreboot.org/fsp.git) registered for path '3rdparty/fsp'
Submodule 'intel-microcode' (https://review.coreboot.org/intel-microcode.git) registered for path '3rdparty/intel-microcode'
Submodule '3rdparty/intel-sec-tools' (https://review.coreboot.org/9esec-security-tooling.git) registered for path '3rdparty/intel-sec-tools'
Submodule 'libgfxinit' (https://review.coreboot.org/libgfxinit.git) registered for path '3rdparty/libgfxinit'
Submodule 'libhwbase' (https://review.coreboot.org/libhwbase.git) registered for path '3rdparty/libhwbase'
Submodule 'opensbi' (https://review.coreboot.org/opensbi.git) registered for path '3rdparty/opensbi'
Submodule '3rdparty/qc_blobs' (https://review.coreboot.org/qc_blobs.git) registered for path '3rdparty/qc_blobs'
Submodule '3rdparty/stm' (https://review.coreboot.org/STM) registered for path '3rdparty/stm'
Submodule 'vboot' (https://review.coreboot.org/vboot.git) registered for path '3rdparty/vboot'
Submodule 'util/nvidia-cbootimage' (https://review.coreboot.org/nvidia-cbootimage.git) registered for path 'util/nvidia/cbootimage'
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/amd_blobs'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/arm-trusted-firmware'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/blobs'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/chromeec'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/cmocka'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/ffs'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/fsp'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/intel-microcode'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/intel-sec-tools'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/libgfxinit'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/libhwbase'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/opensbi'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/qc_blobs'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/stm'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/3rdparty/vboot'...
Cloning into '/root/bios/pce-fw-builder/release/coreboot/util/nvidia/cbootimage'...
Submodule path '3rdparty/amd_blobs': checked out 'd0a92151d387b5296b6c5fbff4e4d66839c5c2dd'
Submodule path '3rdparty/arm-trusted-firmware': checked out 'a4c979ade4438dfdd69c1b6e23b64e88eb648183'
Submodule path '3rdparty/blobs': checked out 'a59fb6e3892f0629d43769a07ee7f1048a0ae1f8'
Submodule path '3rdparty/chromeec': checked out 'a1afae4e002a3eccd7835ac898259b0690e9e61a'
Submodule path '3rdparty/cmocka': checked out '672c5cee79eb412025c3dd8b034e611c1f119055'
Submodule path '3rdparty/ffs': checked out '3ec70fbc458e32eef0d0b1de79688b4dc48cbd57'
Submodule path '3rdparty/fsp': checked out 'eb25f19ef7fbe88fb207c6896a37a2035bba9bc5'
Submodule path '3rdparty/intel-microcode': checked out '0e4288f81f806620c65f70ee2bcf94b69d574096'
Submodule path '3rdparty/intel-sec-tools': checked out 'a86ff5d400983d685d4389c07433452c7a503300'
Submodule path '3rdparty/libgfxinit': checked out '3318bf26803c77d41b18bef6d7ae4e051b97f9f2'
Submodule path '3rdparty/libhwbase': checked out 'a3edc6ef32d09c566b7ea3555bc753458ec63039'
Submodule path '3rdparty/opensbi': checked out '215421ca610a64b8ec188c96ea8588ae2de41fb7'
Submodule path '3rdparty/qc_blobs': checked out '6b7fe498eb782b8f9758f28dd53bb0697be0d0b0'
Submodule path '3rdparty/stm': checked out '1f3258261a4f4d6c60ec4447c7a03acf2509b984'
Submodule path '3rdparty/vboot': checked out '48195e5878006ac2cf74cb7f02953ab06c68202d'
Submodule path 'util/nvidia/cbootimage': checked out '65a6d94dd5f442578551e0a81ecbe5235e673fd4'
remote: Enumerating objects: 3778, done.
remote: Counting objects: 100% (3778/3778), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 11028 (delta 3755), reused 3778 (delta 3755), pack-reused 7250
Receiving objects: 100% (11028/11028), 7.53 MiB | 6.37 MiB/s, done.
Resolving deltas: 100% (7917/7917), completed with 1150 local objects.
From https://github.com/pcengines/coreboot
 * [new branch]            coreboot-4.0.x                 -> pcengines/coreboot-4.0.x
 * [new branch]            coreboot-4.5.x                 -> pcengines/coreboot-4.5.x
 * [new branch]            coreboot-4.6.x                 -> pcengines/coreboot-4.6.x
 * [new branch]            develop                        -> pcengines/develop
 * [new branch]            fosdem2020                     -> pcengines/fosdem2020
 * [new branch]            inconsistent_mtrr_fix          -> pcengines/inconsistent_mtrr_fix
 * [new branch]            ipxe_multiboot2                -> pcengines/ipxe_multiboot2
 * [new branch]            master                         -> pcengines/master
 * [new branch]            memtest-update                 -> pcengines/memtest-update
 * [new branch]            new_spi_and_bootorder          -> pcengines/new_spi_and_bootorder
 * [new branch]            pce_grub_uefi                  -> pcengines/pce_grub_uefi
 * [new branch]            pcengines_trenchboot_4.11.x    -> pcengines/pcengines_trenchboot_4.11.x
 * [new branch]            pcengines_trenchboot_4.12.x    -> pcengines/pcengines_trenchboot_4.12.x
 * [new branch]            pcengines_trenchboot_v4.10.0.2 -> pcengines/pcengines_trenchboot_v4.10.0.2
 * [new branch]            regression-logs-legacy         -> pcengines/regression-logs-legacy
 * [new branch]            regressions-fixes              -> pcengines/regressions-fixes
 * [new branch]            rel_4.13.0.1                   -> pcengines/rel_4.13.0.1
 * [new branch]            release                        -> pcengines/release
 * [new branch]            tianocore_vUDK2018             -> pcengines/tianocore_vUDK2018
 * [new branch]            tpm2_sb_uefi                   -> pcengines/tpm2_sb_uefi
 * [new branch]            tpm2_uefi                      -> pcengines/tpm2_uefi
 * [new branch]            vpd_port                       -> pcengines/vpd_port
 * [new tag]               v4.0.33                        -> v4.0.33
 * [new tag]               v4.13.0.1                      -> v4.13.0.1
 * [new tag]               v4.5.8                         -> v4.5.8
 * [new tag]               v4.6.10                        -> v4.6.10
 * [new tag]               v4.7.0                         -> v4.7.0
 * [new tag]               apu2b-20160304                 -> apu2b-20160304
 * [new tag]               v4.0.1                         -> v4.0.1
 * [new tag]               v4.0.1.1                       -> v4.0.1.1
 * [new tag]               v4.0.10                        -> v4.0.10
 * [new tag]               v4.0.11                        -> v4.0.11
 * [new tag]               v4.0.12                        -> v4.0.12
 * [new tag]               v4.0.13                        -> v4.0.13
 * [new tag]               v4.0.14                        -> v4.0.14
 * [new tag]               v4.0.15                        -> v4.0.15
 * [new tag]               v4.0.16                        -> v4.0.16
 * [new tag]               v4.0.17                        -> v4.0.17
 * [new tag]               v4.0.18                        -> v4.0.18
 * [new tag]               v4.0.19                        -> v4.0.19
 * [new tag]               v4.0.2                         -> v4.0.2
 * [new tag]               v4.0.20                        -> v4.0.20
 * [new tag]               v4.0.21                        -> v4.0.21
 * [new tag]               v4.0.22                        -> v4.0.22
 * [new tag]               v4.0.23                        -> v4.0.23
 * [new tag]               v4.0.24                        -> v4.0.24
 * [new tag]               v4.0.25                        -> v4.0.25
 * [new tag]               v4.0.26                        -> v4.0.26
 * [new tag]               v4.0.27                        -> v4.0.27
 * [new tag]               v4.0.28                        -> v4.0.28
 * [new tag]               v4.0.29                        -> v4.0.29
 * [new tag]               v4.0.3                         -> v4.0.3
 * [new tag]               v4.0.30                        -> v4.0.30
 * [new tag]               v4.0.31                        -> v4.0.31
 * [new tag]               v4.0.32                        -> v4.0.32
 * [new tag]               v4.0.4                         -> v4.0.4
 * [new tag]               v4.0.5                         -> v4.0.5
 * [new tag]               v4.0.6                         -> v4.0.6
 * [new tag]               v4.0.7                         -> v4.0.7
 * [new tag]               v4.0.7.1                       -> v4.0.7.1
 * [new tag]               v4.0.7.2                       -> v4.0.7.2
 * [new tag]               v4.0.8                         -> v4.0.8
 * [new tag]               v4.0.9                         -> v4.0.9
 * [new tag]               v4.10.0.0                      -> v4.10.0.0
 * [new tag]               v4.10.0.1                      -> v4.10.0.1
 * [new tag]               v4.10.0.2                      -> v4.10.0.2
 * [new tag]               v4.10.0.3                      -> v4.10.0.3
 * [new tag]               v4.11.0.1                      -> v4.11.0.1
 * [new tag]               v4.11.0.2                      -> v4.11.0.2
 * [new tag]               v4.11.0.3                      -> v4.11.0.3
 * [new tag]               v4.11.0.4                      -> v4.11.0.4
 * [new tag]               v4.11.0.5                      -> v4.11.0.5
 * [new tag]               v4.11.0.6                      -> v4.11.0.6
 * [new tag]               v4.12.0.1                      -> v4.12.0.1
 * [new tag]               v4.12.0.2                      -> v4.12.0.2
 * [new tag]               v4.12.0.3                      -> v4.12.0.3
 * [new tag]               v4.12.0.4                      -> v4.12.0.4
 * [new tag]               v4.12.0.5                      -> v4.12.0.5
 * [new tag]               v4.12.0.6                      -> v4.12.0.6
 * [new tag]               v4.5.2                         -> v4.5.2
 * [new tag]               v4.5.3                         -> v4.5.3
 * [new tag]               v4.5.3.1                       -> v4.5.3.1
 * [new tag]               v4.5.4                         -> v4.5.4
 * [new tag]               v4.5.5                         -> v4.5.5
 * [new tag]               v4.5.5.1                       -> v4.5.5.1
 * [new tag]               v4.5.5.2                       -> v4.5.5.2
 * [new tag]               v4.5.6                         -> v4.5.6
 * [new tag]               v4.5.7                         -> v4.5.7
 * [new tag]               v4.6.0                         -> v4.6.0
 * [new tag]               v4.6.1                         -> v4.6.1
 * [new tag]               v4.6.2                         -> v4.6.2
 * [new tag]               v4.6.3                         -> v4.6.3
 * [new tag]               v4.6.4                         -> v4.6.4
 * [new tag]               v4.6.5                         -> v4.6.5
 * [new tag]               v4.6.6                         -> v4.6.6
 * [new tag]               v4.6.7                         -> v4.6.7
 * [new tag]               v4.6.8                         -> v4.6.8
 * [new tag]               v4.6.9                         -> v4.6.9
 * [new tag]               v4.8.0.1                       -> v4.8.0.1
 * [new tag]               v4.8.0.2                       -> v4.8.0.2
 * [new tag]               v4.8.0.3                       -> v4.8.0.3
 * [new tag]               v4.8.0.4                       -> v4.8.0.4
 * [new tag]               v4.8.0.5                       -> v4.8.0.5
 * [new tag]               v4.8.0.6                       -> v4.8.0.6
 * [new tag]               v4.8.0.7                       -> v4.8.0.7
 * [new tag]               v4.9.0.1                       -> v4.9.0.1
 * [new tag]               v4.9.0.2                       -> v4.9.0.2
 * [new tag]               v4.9.0.3                       -> v4.9.0.3
 * [new tag]               v4.9.0.4                       -> v4.9.0.4
 * [new tag]               v4.9.0.5                       -> v4.9.0.5
 * [new tag]               v4.9.0.6                       -> v4.9.0.6
 * [new tag]               v4.9.0.7                       -> v4.9.0.7
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Total 9 (delta 8), reused 8 (delta 8), pack-reused 1
Unpacking objects: 100% (9/9), done.
From https://github.com/pcengines/coreboot
 * [new tag]               v4.5.1     -> v4.5.1
Note: checking out 'v4.13.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 90d697891f Merge pull request #452 from pcengines/rel_4.13.0.1
Submodule path '3rdparty/amd_blobs': checked out '8c668ab552a02724a07f8c6e7285a5f21a61569b'
Submodule path '3rdparty/vboot': checked out '9d4053df76c127f625a8571d3ef16e6a063c8de5'
Release apu2 build coreboot mainline
Build coreboot for apu2
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
/bin/sh: 1: cannot create .dependencies: Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
/bin/sh: 1: cannot create .dependencies: Permission denied
cp: cannot create regular file '.config': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
Error: Expected config file (/home/coreboot/coreboot/.config) not present.
Please specify a config file or run 'make menuconfig' to
generate a new config file.
make: *** [Makefile:142: real-all] Error 1
cp: nelze získat informace o 'coreboot/build/coreboot.rom': Adresář nebo soubor neexistuje
sha256sum: apu2_v4.13.0.1.rom: Adresář nebo soubor neexistuje`

**Comment by pkonkol** [comment]
@vecinohk Updated docker image will be pushed to dockerhub today

**Comment by pkonkol** [comment]
@vecinohk Done. It should work now.

**Comment by vecinohk** [comment]
@pkonkol I deleted all docker containers ... but Am I doing it right?

1) git clone https://github.com/pcengines/pce-fw-builder.git
2) after that: "and after run: "./build.sh release v4.13.0.1 apu2"

```
Unable to find image 'pcengines/pce-fw-builder:1.52.1' locally
1.52.1: Pulling from pcengines/pce-fw-builder
26254fbb7f1e: Pull complete 
bf29263a5816: Pull complete 
158654ea46e3: Pull complete 
46f27340da7f: Pull complete 
Digest: sha256:c0c10ea2e8b3f8150843f1b7e93d515f63095cbbfc5b04eb08e404e658221184
Status: Downloaded newer image for pcengines/pce-fw-builder:1.52.1
Build coreboot for apu2
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
...
```

**Comment by miczyg1** [comment]
This line tells the builder to use 1.52.1: https://github.com/pcengines/pce-fw-builder/blob/master/build.sh#L113
@pkonkol you forgot to change it, please do it.

@vecinohk if you change the line above to 1.52.4, then it will work

**Comment by vecinohk** [comment]
@miczyg1 I change to 1.52.4:

```
Release apu2 build coreboot mainline
Unable to find image 'pcengines/pce-fw-builder:1.52.4' locally
1.52.4: Pulling from pcengines/pce-fw-builder
26254fbb7f1e: Pull complete 
bf29263a5816: Pull complete 
158654ea46e3: Pull complete 
46f27340da7f: Pull complete 
f58abf0c27d8: Pull complete 
ff96c7709909: Pull complete 
Digest: sha256:f0dd911abdbc414f970fa22507e0387169dfbce320342f22675e09b914473326
Status: Downloaded newer image for pcengines/pce-fw-builder:1.52.4
usermod: UID '0' already exists
Build coreboot for apu2
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
/bin/sh: 1: cannot create .dependencies: Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
/bin/sh: 1: cannot create .dependencies: Permission denied
cp: cannot create regular file '.config': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
Error: Expected config file (/home/coreboot/coreboot/.config) not present.
Please specify a config file or run 'make menuconfig' to
generate a new config file.
make: *** [Makefile:142: real-all] Error 1
```

**Comment by miczyg1** [comment]
@vecinohk it looks like it tries to assign UID 0 (root) to the inner user in docker container. Do you run the build process as root user?

**Comment by vecinohk** [comment]
Yes like root.

**Comment by macpijan** [comment]
@vecinohk Do you need to run the docker as root? Generally, this should be avoided. Instead, you should add your user to docker group and run docker as a regular user (not root). https://docs.docker.com/engine/install/linux-postinstall/

**Comment by vecinohk** [comment]
@macpijan Yep - you are right... without root is all ok ... sorry for that - I do not friend with Docker.

Many thanks to: @pkonkol @miczyg1 @macpijan

**Comment by krbvroc1** [comment]
@pkonkol @miczyg1 

This is still not fixed, in the sense that as a new user, I just fetched and ran into this issue trying to build the latest v4.13.0.5 for APU2. I found my way to this closed issue and notice the above comment that 1.52.1 is hard coded into the build.sh. Is there any technical  reason the build.sh has not been updated to 1.52.4, almost 5 months later?
https://github.com/pcengines/pce-fw-builder/blob/master/build.sh#L113
